/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import models.UndirectedGraph;
import service.ViewServices;

/**
 *
 * @author elev
 */
public class MenuFrame extends javax.swing.JFrame {
        DefaultListModel listModel; 
    
    
    public MenuFrame() {
        initComponents();
        
        listModel = new DefaultListModel();
        jList1.setModel(listModel);
        initJList1();
        
        jList1.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent ev){
                if(ev.getClickCount()==2){
                    String command = jList1.getSelectedValue();
                    int commandProcessed = ViewServices.processCommand(command); 
                    System.out.println(commandProcessed);
                    executeCommand(commandProcessed);
                }
            }
        
        });
        
        
        setVisible(true);
        setLocationRelativeTo(null);
        setSize(720,480);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initJList1() {
        List<String> list = ViewServices.getDemands();
        list.forEach(listModel::addElement);
    }
    
    private void executeCommand(int command){
        switch(command){
            case 1: 
                UndirectedGraph uGraph = UndirectedGraph.getInitGraph();
                AdjacencyMatrixFrame amf = new AdjacencyMatrixFrame();
                break;
            default:System.out.println(0);
        }
            
    }

   
}
